(define (problem Fuuu)
  (:domain Shakey)
  (:objects robot room1 room2)
  (:init 
		(robot ?robot1)
		(room ?room1)
		(room ?room2)
		(room ?room3)
		(at ?robot1 ?room1)
		(adjacent ?room1 ?room2)
		(adjacent ?room2 ?room3)
	)
  (:goal (at ?robot1 ?room1))
  )
